name: Deploy to AWS S3
on: 
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-2
  BUILD_PATH: dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: CI=false npm run build
        env:
          VITE_APP_LOGIN_EMAIL: ${{ secrets.VITE_APP_LOGIN_EMAIL }}
          VITE_APP_LOGIN_PASSWORD: ${{ secrets.VITE_APP_LOGIN_PASSWORD }}
          VITE_APP_POST_AND_GET_CAMPAIGNS: ${{secrets.VITE_APP_POST_AND_GET_CAMPAIGNS}}
          VITE_APP_POST_UNSUSCRIBE_USERS: ${{secrets.VITE_APP_POST_UNSUSCRIBE_USERS}}
          VITE_APP_POST_LOGIN: ${{secrets.VITE_APP_POST_LOGIN}}
          VITE_APP_GET_SUPRESSION_LIST: ${{secrets.VITE_APP_GET_SUPRESSION_LIST}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ${{ env.BUILD_PATH }} s3://${{ secrets.AWS_S3_BUCKET }} --delete
  
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

